import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
const isDashboard = true;

  return (
    <html lang="en">
      <body>
        {isDashboard && <Header />}
        {children}
        {isDashboard && <Footer />}
      </body>
    </html>
  );
}